"""add_meeting_link_to_task

Revision ID: 8062a2186fd3
Revises: a780ee847be6
Create Date: 2026-09-18 10:39:20.468856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8062a2186fd3'
down_revision: Union[str, None] = 'a780ee847be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('meeting_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'meeting_link')
    # ### end Alembic commands ###
