"""add_intent_to_task

Revision ID: a780ee847be6
Revises: d356ac68866e
Create Date: 2026-09-16 15:23:37.868907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a780ee847be6'
down_revision: Union[str, None] = 'd356ac68866e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('intent', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'intent')
    # ### end Alembic commands ###
