"""add translations to transcript

Revision ID: d356ac68866e
Revises: 6518f5c617cd
Create Date: 2026-09-14 11:35:19.083415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd356ac68866e'
down_revision: Union[str, None] = '6518f5c617cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('translation_english', sa.Text(), nullable=True))
    op.add_column('transcripts', sa.Column('translation_urdu', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'translation_urdu')
    op.drop_column('transcripts', 'translation_english')
    # ### end Alembic commands ###
